events {}

http {
    resolver 127.0.0.11 valid=5s;

    upstream application {
        zone application 64k;
        server application:8080 resolve;
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://application;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
